export const INIT_ROLE_PERMISSION = [
  { roleId: 2, permissionId: 2 },
  { roleId: 2, permissionId: 3 },
  { roleId: 2, permissionId: 4 },
  { roleId: 2, permissionId: 5 },
  { roleId: 2, permissionId: 6 },
  { roleId: 2, permissionId: 7 },
  { roleId: 2, permissionId: 8 },
  { roleId: 2, permissionId: 9 },
  { roleId: 2, permissionId: 10 },
  { roleId: 2, permissionId: 11 },

  { roleId: 4, permissionId: 2 },
  { roleId: 4, permissionId: 3 },
  { roleId: 4, permissionId: 4 },
  { roleId: 4, permissionId: 5 },
  { roleId: 4, permissionId: 6 },
  { roleId: 4, permissionId: 7 },
  { roleId: 4, permissionId: 8 },
  { roleId: 4, permissionId: 9 },
  { roleId: 4, permissionId: 10 },
  { roleId: 4, permissionId: 11 },

  { roleId: 5, permissionId: 2 },
  { roleId: 5, permissionId: 3 },
  { roleId: 5, permissionId: 4 },
  { roleId: 5, permissionId: 5 },
  { roleId: 5, permissionId: 6 },
  { roleId: 5, permissionId: 7 },
  { roleId: 5, permissionId: 8 },
  { roleId: 5, permissionId: 9 },
  { roleId: 5, permissionId: 10 },
  { roleId: 5, permissionId: 11 },
];
