export const INIT_ALLCODE = [
  // ===== COUNTRY =====
  {
    keyMap: 'C_ALL',
    type: 'COUNTRY',
    valueEn: 'All',
    valueVi: 'Tất cả',
    description: 'Tất cả quốc gia',
  },
  {
    keyMap: 'C_VN',
    type: 'COUNTRY',
    valueEn: 'Vietnam',
    valueVi: 'Việt Nam',
    description: 'Quốc gia Việt Nam',
  },
  {
    keyMap: 'C_US',
    type: 'COUNTRY',
    valueEn: 'USA',
    valueVi: 'Mỹ',
    description: 'Quốc gia Mỹ',
  },
  {
    keyMap: 'C_KR',
    type: 'COUNTRY',
    valueEn: 'Korea',
    valueVi: 'Hàn Quốc',
    description: 'Quốc gia Hàn Quốc',
  },
  {
    keyMap: 'C_CN',
    type: 'COUNTRY',
    valueEn: 'China',
    valueVi: 'Trung Quốc',
    description: 'Quốc gia Trung Quốc',
  },
  {
    keyMap: 'C_JP',
    type: 'COUNTRY',
    valueEn: 'Japan',
    valueVi: 'Nhật Bản',
    description: 'Quốc gia Nhật Bản',
  },
  {
    keyMap: 'C_HK',
    type: 'COUNTRY',
    valueEn: 'Hong Kong',
    valueVi: 'Hồng Kông',
    description: 'Quốc gia Hồng Kông',
  },
  {
    keyMap: 'C_FR',
    type: 'COUNTRY',
    valueEn: 'France',
    valueVi: 'Pháp',
    description: 'Quốc gia Pháp',
  },
  {
    keyMap: 'C_TH',
    type: 'COUNTRY',
    valueEn: 'Thailand',
    valueVi: 'Thái Lan',
    description: 'Quốc gia Thái Lan',
  },
  {
    keyMap: 'C_UK',
    type: 'COUNTRY',
    valueEn: 'UK',
    valueVi: 'Anh',
    description: 'Quốc gia Anh',
  },
  {
    keyMap: 'C_DE',
    type: 'COUNTRY',
    valueEn: 'Germany',
    valueVi: 'Đức',
    description: 'Quốc gia Đức',
  },
  {
    keyMap: 'C_TW',
    type: 'COUNTRY',
    valueEn: 'Taiwan',
    valueVi: 'Đài Loan',
    description: 'Quốc gia Đài Loan',
  },
  {
    keyMap: 'C_AU',
    type: 'COUNTRY',
    valueEn: 'Australia',
    valueVi: 'Úc',
    description: 'Quốc gia Úc',
  },
  {
    keyMap: 'C_CA',
    type: 'COUNTRY',
    valueEn: 'Canada',
    valueVi: 'Canada',
    description: 'Quốc gia Canada',
  },

  // ===== FILM_TYPE =====
  {
    keyMap: 'FT_ALL',
    type: 'FILM_TYPE',
    valueEn: 'All',
    valueVi: 'Tất cả',
    description: 'Tất cả loại phim',
  },
  {
    keyMap: 'FT_SINGLE',
    type: 'FILM_TYPE',
    valueEn: 'Single',
    valueVi: 'Phim lẻ',
    description: 'Phim lẻ',
  },
  {
    keyMap: 'FT_SERIES',
    type: 'FILM_TYPE',
    valueEn: 'Series',
    valueVi: 'Phim bộ',
    description: 'Phim bộ',
  },

  // ===== RANK =====
  {
    keyMap: 'R_ALL',
    type: 'RANK',
    valueEn: 'All',
    valueVi: 'Tất cả',
    description: 'Tất cả độ tuổi',
  },
  {
    keyMap: 'R_P',
    type: 'RANK',
    valueEn: 'P',
    valueVi: 'Mọi lứa tuổi',
    description: 'Phim cho mọi lứa tuổi',
  },
  {
    keyMap: 'R_K',
    type: 'RANK',
    valueEn: 'K',
    valueVi: 'Dưới 13 tuổi',
    description: 'Khán giả dưới 13 tuổi',
  },
  {
    keyMap: 'R_T13',
    type: 'RANK',
    valueEn: 'T13',
    valueVi: '13 tuổi trở lên',
    description: 'Khán giả từ 13+',
  },
  {
    keyMap: 'R_T16',
    type: 'RANK',
    valueEn: 'T16',
    valueVi: '16 tuổi trở lên',
    description: 'Khán giả từ 16+',
  },
  {
    keyMap: 'R_T18',
    type: 'RANK',
    valueEn: 'T18',
    valueVi: '18 tuổi trở lên',
    description: 'Khán giả từ 18+',
  },

  // ===== GENRE =====
  {
    keyMap: 'G_ALL',
    type: 'GENRE',
    valueEn: 'All',
    valueVi: 'Tất cả',
    description: 'Tất cả thể loại',
  },
  {
    keyMap: 'G_ANIME',
    type: 'GENRE',
    valueEn: 'Anime',
    valueVi: 'Anime',
    description: 'Phim Anime',
  },
  {
    keyMap: 'G_ACTION',
    type: 'GENRE',
    valueEn: 'Action',
    valueVi: 'Hành Động',
    description: 'Phim hành động',
  },
  {
    keyMap: 'G_COMEDY',
    type: 'GENRE',
    valueEn: 'Comedy',
    valueVi: 'Hài',
    description: 'Phim hài',
  },
  {
    keyMap: 'G_ROMANCE',
    type: 'GENRE',
    valueEn: 'Romance',
    valueVi: 'Tình Cảm',
    description: 'Phim tình cảm',
  },
  {
    keyMap: 'G_HORROR',
    type: 'GENRE',
    valueEn: 'Horror',
    valueVi: 'Kinh Dị',
    description: 'Phim kinh dị',
  },
  {
    keyMap: 'G_SCIFI',
    type: 'GENRE',
    valueEn: 'Sci-Fi',
    valueVi: 'Khoa Học Viễn Tưởng',
    description: 'Phim khoa học viễn tưởng',
  },
  {
    keyMap: 'G_FANTASY',
    type: 'GENRE',
    valueEn: 'Fantasy',
    valueVi: 'Kỳ Ảo',
    description: 'Phim kỳ ảo',
  },
  {
    keyMap: 'G_HISTORY',
    type: 'GENRE',
    valueEn: 'History',
    valueVi: 'Lịch Sử',
    description: 'Phim lịch sử',
  },
  {
    keyMap: 'G_WAR',
    type: 'GENRE',
    valueEn: 'War',
    valueVi: 'Chiến Tranh',
    description: 'Phim chiến tranh',
  },
  {
    keyMap: 'G_DOC',
    type: 'GENRE',
    valueEn: 'Documentary',
    valueVi: 'Tài Liệu',
    description: 'Phim tài liệu',
  },
  {
    keyMap: 'G_FAMILY',
    type: 'GENRE',
    valueEn: 'Family',
    valueVi: 'Gia Đình',
    description: 'Phim gia đình',
  },
  {
    keyMap: 'G_THRILLER',
    type: 'GENRE',
    valueEn: 'Thriller',
    valueVi: 'Gay Cấn',
    description: 'Phim gay cấn',
  },
  {
    keyMap: 'G_MUSICAL',
    type: 'GENRE',
    valueEn: 'Musical',
    valueVi: 'Nhạc Kịch',
    description: 'Phim nhạc kịch',
  },
  {
    keyMap: 'G_SPORT',
    type: 'GENRE',
    valueEn: 'Sport',
    valueVi: 'Thể Thao',
    description: 'Phim thể thao',
  },
  {
    keyMap: 'G_DETECTIVE',
    type: 'GENRE',
    valueEn: 'Detective',
    valueVi: 'Trinh Thám',
    description: 'Phim trinh thám',
  },
  {
    keyMap: 'G_SCHOOL',
    type: 'GENRE',
    valueEn: 'School',
    valueVi: 'Học Đường',
    description: 'Phim học đường',
  },
  {
    keyMap: 'G_SUPERHERO',
    type: 'GENRE',
    valueEn: 'Superhero',
    valueVi: 'Siêu Anh Hùng',
    description: 'Phim siêu anh hùng',
  },
  {
    keyMap: 'G_MAGIC',
    type: 'GENRE',
    valueEn: 'Magic',
    valueVi: 'Phép Thuật',
    description: 'Phim phép thuật',
  },
  {
    keyMap: 'G_MYTH',
    type: 'GENRE',
    valueEn: 'Mythology',
    valueVi: 'Thần Thoại',
    description: 'Phim thần thoại',
  },
  {
    keyMap: 'G_LGBT',
    type: 'GENRE',
    valueEn: 'LGBT+',
    valueVi: 'LGBT+',
    description: 'Phim LGBT+',
  },

  // ===== VERSION =====
  {
    keyMap: 'V_ALL',
    type: 'VERSION',
    valueEn: 'All',
    valueVi: 'Tất cả',
    description: 'Tất cả phiên bản',
  },
  {
    keyMap: 'V_SUB',
    type: 'VERSION',
    valueEn: 'Subtitle',
    valueVi: 'Phụ đề',
    description: 'Phim có phụ đề',
  },
  {
    keyMap: 'V_DUB',
    type: 'VERSION',
    valueEn: 'Dubbed',
    valueVi: 'Lồng tiếng',
    description: 'Phim lồng tiếng',
  },
  {
    keyMap: 'V_VOICE_NORTH',
    type: 'VERSION',
    valueEn: 'Voice North',
    valueVi: 'Thuyết minh giọng Bắc',
    description: 'Thuyết minh miền Bắc',
  },
  {
    keyMap: 'V_VOICE_SOUTH',
    type: 'VERSION',
    valueEn: 'Voice South',
    valueVi: 'Thuyết minh giọng Nam',
    description: 'Thuyết minh miền Nam',
  },

  // ===== YEAR =====
  {
    keyMap: 'Y_ALL',
    type: 'YEAR',
    valueEn: 'All',
    valueVi: 'Tất cả',
    description: 'Tất cả năm',
  },
  {
    keyMap: 'Y_2025',
    type: 'YEAR',
    valueEn: '2025',
    valueVi: '2025',
    description: 'Năm 2025',
  },
  {
    keyMap: 'Y_2024',
    type: 'YEAR',
    valueEn: '2024',
    valueVi: '2024',
    description: 'Năm 2024',
  },
  {
    keyMap: 'Y_2023',
    type: 'YEAR',
    valueEn: '2023',
    valueVi: '2023',
    description: 'Năm 2023',
  },
  {
    keyMap: 'Y_2022',
    type: 'YEAR',
    valueEn: '2022',
    valueVi: '2022',
    description: 'Năm 2022',
  },
  {
    keyMap: 'Y_2021',
    type: 'YEAR',
    valueEn: '2021',
    valueVi: '2021',
    description: 'Năm 2021',
  },
  {
    keyMap: 'Y_2020',
    type: 'YEAR',
    valueEn: '2020',
    valueVi: '2020',
    description: 'Năm 2020',
  },
  {
    keyMap: 'Y_2019',
    type: 'YEAR',
    valueEn: '2019',
    valueVi: '2019',
    description: 'Năm 2019',
  },
  {
    keyMap: 'Y_2018',
    type: 'YEAR',
    valueEn: '2018',
    valueVi: '2018',
    description: 'Năm 2018',
  },
  {
    keyMap: 'Y_2017',
    type: 'YEAR',
    valueEn: '2017',
    valueVi: '2017',
    description: 'Năm 2017',
  },
  {
    keyMap: 'Y_2016',
    type: 'YEAR',
    valueEn: '2016',
    valueVi: '2016',
    description: 'Năm 2016',
  },
  {
    keyMap: 'Y_2015',
    type: 'YEAR',
    valueEn: '2015',
    valueVi: '2015',
    description: 'Năm 2015',
  },
  {
    keyMap: 'Y_2014',
    type: 'YEAR',
    valueEn: '2014',
    valueVi: '2014',
    description: 'Năm 2014',
  },
  {
    keyMap: 'Y_2013',
    type: 'YEAR',
    valueEn: '2013',
    valueVi: '2013',
    description: 'Năm 2013',
  },
  {
    keyMap: 'Y_2012',
    type: 'YEAR',
    valueEn: '2012',
    valueVi: '2012',
    description: 'Năm 2012',
  },
  {
    keyMap: 'Y_2011',
    type: 'YEAR',
    valueEn: '2011',
    valueVi: '2011',
    description: 'Năm 2011',
  },
  {
    keyMap: 'Y_2010',
    type: 'YEAR',
    valueEn: '2010',
    valueVi: '2010',
    description: 'Năm 2010',
  },

  // ===== SORT =====
  {
    keyMap: 'S_NEW',
    type: 'SORT',
    valueEn: 'Newest',
    valueVi: 'Mới nhất',
    description: 'Phim mới nhất',
  },
  {
    keyMap: 'S_UPDATE',
    type: 'SORT',
    valueEn: 'Latest Update',
    valueVi: 'Mới cập nhật',
    description: 'Phim mới cập nhật',
  },
  {
    keyMap: 'S_IMDB',
    type: 'SORT',
    valueEn: 'IMDb Score',
    valueVi: 'Điểm IMDb',
    description: 'Sắp xếp theo IMDb',
  },
  {
    keyMap: 'S_VIEW',
    type: 'SORT',
    valueEn: 'Views',
    valueVi: 'Lượt xem',
    description: 'Sắp xếp theo lượt xem',
  },

  // ===== GENDER =====
  {
    keyMap: 'M',
    type: 'GENDER',
    valueEn: 'Male',
    valueVi: 'Nam',
    description: 'Giới tính Nam',
  },
  {
    keyMap: 'F',
    type: 'GENDER',
    valueEn: 'Female',
    valueVi: 'Nữ',
    description: 'Giới tính Nữ',
  },
  {
    keyMap: 'O',
    type: 'GENDER',
    valueEn: 'Other',
    valueVi: 'Khác',
    description: 'Giới tính khác',
  },

  // ===== ROLE =====
  {
    keyMap: 'ROLE_ADMIN',
    type: 'ROLE',
    valueEn: 'Admin',
    valueVi: 'Quản trị viên',
    description: 'Có full quyền',
  },
  {
    keyMap: 'ROLE_MOD',
    type: 'ROLE',
    valueEn: 'Moderator',
    valueVi: 'Người kiểm duyệt',
    description: 'Kiểm duyệt nội dung',
  },
  {
    keyMap: 'ROLE_USER',
    type: 'ROLE',
    valueEn: 'User',
    valueVi: 'Người dùng',
    description: 'Người dùng cơ bản',
  },

  // ===== USER_STATUS =====
  {
    keyMap: 'US_ACTIVE',
    type: 'USER_STATUS',
    valueEn: 'Active',
    valueVi: 'Hoạt động',
    description: 'Tài khoản người dùng đang hoạt động bình thường',
  },
  {
    keyMap: 'US_INACTIVE',
    type: 'USER_STATUS',
    valueEn: 'Inactive',
    valueVi: 'Không hoạt động',
    description:
      'Tài khoản chưa được kích hoạt hoặc đã bị vô hiệu hóa tạm thời',
  },
  {
    keyMap: 'US_BANNED',
    type: 'USER_STATUS',
    valueEn: 'Banned',
    valueVi: 'Đã bị khóa',
    description: 'Tài khoản vi phạm và bị cấm sử dụng hệ thống',
  },

  // ===== FILM_STATUS =====
  {
    keyMap: 'FS_COMING_SOON',
    type: 'FILM_STATUS',
    valueEn: 'Coming Soon',
    valueVi: 'Sắp chiếu',
    description: 'Phim đã lên lịch và chuẩn bị công chiếu',
  },
  {
    keyMap: 'FS_SHOWING',
    type: 'FILM_STATUS',
    valueEn: 'Now Showing',
    valueVi: 'Đang chiếu',
    description: 'Phim hiện đang được chiếu trên hệ thống',
  },
  {
    keyMap: 'FS_STOPPED',
    type: 'FILM_STATUS',
    valueEn: 'Stopped',
    valueVi: 'Ngừng chiếu',
    description: 'Phim đã ngừng chiếu hoặc bị gỡ khỏi hệ thống',
  },
];
