export const INIT_PERMISSIONS = [
  {
    name: 'Create a new actor',
    apiPath: '/api/v1/actor/create-actor',
    method: 'POST',
    module: 'ACTOR',
  },
  {
    name: 'Get all actors with pagination, filtering, and sorting',
    apiPath: '/api/v1/actor/all-actors',
    method: 'GET',
    module: 'ACTOR',
  },
  {
    name: 'Get actor by ID',
    apiPath: '/api/v1/actor/get-actor-by-id/:actorId',
    method: 'GET',
    module: 'ACTOR',
  },
  {
    name: 'Update actor by ID',
    apiPath: '/api/v1/actor/update-actor/:actorId',
    method: 'PATCH',
    module: 'ACTOR',
  },
  {
    name: 'Delete actor by ID',
    apiPath: '/api/v1/actor/delete-actor-by-id/:actorId',
    method: 'DELETE',
    module: 'ACTOR',
  },
  {
    name: 'Create all code',
    apiPath: '/api/v1/all-codes',
    method: 'POST',
    module: 'ALL-CODES',
  },
  {
    name: 'Get all codes',
    apiPath: '/api/v1/all-codes',
    method: 'GET',
    module: 'ALL-CODES',
  },
  {
    name: 'Get all code by id',
    apiPath: '/api/v1/all-codes/:id',
    method: 'GET',
    module: 'ALL-CODES',
  },
  {
    name: 'Update all code',
    apiPath: '/api/v1/all-codes/:id',
    method: 'PATCH',
    module: 'ALL-CODES',
  },
  {
    name: 'Delete all code',
    apiPath: '/api/v1/all-codes/:id',
    method: 'DELETE',
    module: 'ALL-CODES',
  },
  {
    name: 'User Login',
    apiPath: '/api/v1/auth/login',
    method: 'POST',
    module: 'AUTH',
  },
  {
    name: 'Get User by refresh token',
    apiPath: '/api/v1/auth/refreshToken',
    method: 'GET',
    module: 'AUTH',
  },
  {
    name: 'Register a new user',
    apiPath: '/api/v1/auth/register',
    method: 'POST',
    module: 'AUTH',
  },
  {
    name: 'Logout User',
    apiPath: '/api/v1/auth/logout',
    method: 'POST',
    module: 'AUTH',
  },
  {
    name: 'Create a new director',
    apiPath: '/api/v1/director/create-director',
    method: 'POST',
    module: 'DIRECTOR',
  },
  {
    name: 'Get all directors with pagination, filtering, and sorting',
    apiPath: '/api/v1/director/get-all-directors',
    method: 'GET',
    module: 'DIRECTOR',
  },
  {
    name: 'Get director by ID',
    apiPath: '/api/v1/director/get-director-by-id/:directorId',
    method: 'GET',
    module: 'DIRECTOR',
  },
  {
    name: 'Edit director by ID',
    apiPath: '/api/v1/director/edit-director/:directorId',
    method: 'PATCH',
    module: 'DIRECTOR',
  },
  {
    name: 'Delete director by ID',
    apiPath: '/api/v1/director/delete-director-by-id/:directorId',
    method: 'DELETE',
    module: 'DIRECTOR',
  },
  {
    name: 'Create episode',
    apiPath: '/api/v1/episodes',
    method: 'POST',
    module: 'EPISODES',
  },
  {
    name: 'Get all episodes',
    apiPath: '/api/v1/episodes',
    method: 'GET',
    module: 'EPISODES',
  },
  {
    name: 'Get episode by id',
    apiPath: '/api/v1/episodes/:id',
    method: 'GET',
    module: 'EPISODES',
  },
  {
    name: 'Update episode',
    apiPath: '/api/v1/episodes/:id',
    method: 'PATCH',
    module: 'EPISODES',
  },
  {
    name: 'Delete episode',
    apiPath: '/api/v1/episodes/:id',
    method: 'DELETE',
    module: 'EPISODES',
  },
  {
    name: 'Upload file',
    apiPath: '/api/v1/file/upload',
    method: 'POST',
    module: 'FILE',
  },
  {
    name: 'Create relation between film and actor',
    apiPath: '/api/v1/film-actor/create-film-actor',
    method: 'POST',
    module: 'FILM-ACTOR',
  },
  {
    name: 'Get all film-actor relations',
    apiPath: '/api/v1/film-actor/all-film-actors',
    method: 'GET',
    module: 'FILM-ACTOR',
  },
  {
    name: 'Get film-actor relation by id',
    apiPath: '/api/v1/film-actor/get-film-actor-by-id/:id',
    method: 'GET',
    module: 'FILM-ACTOR',
  },
  {
    name: 'Get actors by film id',
    apiPath: '/api/v1/film-actor/get-actors-by-film/:filmId',
    method: 'GET',
    module: 'FILM-ACTOR',
  },
  {
    name: 'Update film-actor relation by id',
    apiPath: '/api/v1/film-actor/edit-film-actor/:id',
    method: 'PATCH',
    module: 'FILM-ACTOR',
  },
  {
    name: 'Delete film-actor relation by id',
    apiPath: '/api/v1/film-actor/delete-film-actor-by-id/:id',
    method: 'DELETE',
    module: 'FILM-ACTOR',
  },
  {
    name: 'Create relation between film and director',
    apiPath: '/api/v1/film-director/create-film-director',
    method: 'POST',
    module: 'FILM-DIRECTOR',
  },
  {
    name: 'Get all film-director relations',
    apiPath: '/api/v1/film-director/all-film-directors',
    method: 'GET',
    module: 'FILM-DIRECTOR',
  },
  {
    name: 'Get film-director relation by id',
    apiPath: '/api/v1/film-director/get-film-director-by-id/:id',
    method: 'GET',
    module: 'FILM-DIRECTOR',
  },
  {
    name: 'Get directors by film',
    apiPath: '/api/v1/film-director/by-film/:filmId',
    method: 'GET',
    module: 'FILM-DIRECTOR',
  },
  {
    name: 'Get films by director',
    apiPath: '/api/v1/film-director/by-director/:directorId',
    method: 'GET',
    module: 'FILM-DIRECTOR',
  },
  {
    name: 'Update film-director relation',
    apiPath: '/api/v1/film-director/edit-film-director/:id',
    method: 'PATCH',
    module: 'FILM-DIRECTOR',
  },
  {
    name: 'Delete film-director relation',
    apiPath: '/api/v1/film-director/delete-film-director/:id',
    method: 'DELETE',
    module: 'FILM-DIRECTOR',
  },
  {
    name: 'Create film',
    apiPath: '/api/v1/films',
    method: 'POST',
    module: 'FILMS',
  },
  {
    name: 'Get all films',
    apiPath: '/api/v1/films',
    method: 'GET',
    module: 'FILMS',
  },
  {
    name: 'Get film by id',
    apiPath: '/api/v1/films/:id',
    method: 'GET',
    module: 'FILMS',
  },
  {
    name: 'Update film',
    apiPath: '/api/v1/films/:id',
    method: 'PATCH',
    module: 'FILMS',
  },
  {
    name: 'Soft delete film',
    apiPath: '/api/v1/films/:id',
    method: 'DELETE',
    module: 'FILMS',
  },
  {
    name: 'Create markdown',
    apiPath: '/api/v1/markdowns',
    method: 'POST',
    module: 'MARKDOWNS',
  },
  {
    name: 'Get all markdowns',
    apiPath: '/api/v1/markdowns',
    method: 'GET',
    module: 'MARKDOWNS',
  },
  {
    name: 'Get markdown by id',
    apiPath: '/api/v1/markdowns/:id',
    method: 'GET',
    module: 'MARKDOWNS',
  },
  {
    name: 'Update markdown',
    apiPath: '/api/v1/markdowns/:id',
    method: 'PATCH',
    module: 'MARKDOWNS',
  },
  {
    name: 'Delete markdown',
    apiPath: '/api/v1/markdowns/:id',
    method: 'DELETE',
    module: 'MARKDOWNS',
  },
  {
    name: 'Create part',
    apiPath: '/api/v1/parts',
    method: 'POST',
    module: 'PARTS',
  },
  {
    name: 'Get all parts by film',
    apiPath: '/api/v1/parts/film',
    method: 'POST',
    module: 'PARTS',
  },
  {
    name: 'Get part by id',
    apiPath: '/api/v1/parts/:id',
    method: 'GET',
    module: 'PARTS',
  },
  {
    name: 'Update part',
    apiPath: '/api/v1/parts/:id',
    method: 'PATCH',
    module: 'PARTS',
  },
  {
    name: 'Delete part',
    apiPath: '/api/v1/parts/:id',
    method: 'DELETE',
    module: 'PARTS',
  },
  {
    name: 'Create a new permission',
    apiPath: '/api/v1/permissions',
    method: 'POST',
    module: 'PERMISSIONS',
  },
  {
    name: 'Fetch all permission',
    apiPath: '/api/v1/permissions',
    method: 'GET',
    module: 'PERMISSIONS',
  },
  {
    name: 'Fetch permissions with pagination',
    apiPath: '/api/v1/permissions/get-permission-with-pagination',
    method: 'GET',
    module: 'PERMISSIONS',
  },
  {
    name: 'Fetch a permission by id',
    apiPath: '/api/v1/permissions/:id',
    method: 'GET',
    module: 'PERMISSIONS',
  },
  {
    name: 'Update a permission',
    apiPath: '/api/v1/permissions/:id',
    method: 'PATCH',
    module: 'PERMISSIONS',
  },
  {
    name: 'Delete a permission',
    apiPath: '/api/v1/permissions/:id',
    method: 'DELETE',
    module: 'PERMISSIONS',
  },
  {
    name: 'Create role permission',
    apiPath: '/api/v1/role-permission',
    method: 'POST',
    module: 'ROLE-PERMISSION',
  },
  {
    name: 'Delete a role permission',
    apiPath: '/api/v1/role-permission/delete',
    method: 'DELETE',
    module: 'ROLE-PERMISSION',
  },
  {
    name: 'Get all permissions by role',
    apiPath: '/api/v1/role-permission/by-role/:roleId',
    method: 'GET',
    module: 'ROLE-PERMISSION',
  },
  {
    name: 'Get all roles by permission',
    apiPath: '/api/v1/role-permission/by-permission/:permissionId',
    method: 'GET',
    module: 'ROLE-PERMISSION',
  },
  {
    name: 'Create a Role',
    apiPath: '/api/v1/roles',
    method: 'POST',
    module: 'ROLES',
  },
  {
    name: 'Get all roles',
    apiPath: '/api/v1/roles',
    method: 'GET',
    module: 'ROLES',
  },
  {
    name: 'Get a role by id',
    apiPath: '/api/v1/roles/:id',
    method: 'GET',
    module: 'ROLES',
  },
  {
    name: 'Update a role',
    apiPath: '/api/v1/roles/:id',
    method: 'PATCH',
    module: 'ROLES',
  },
  {
    name: 'Delete a role',
    apiPath: '/api/v1/roles/:id',
    method: 'DELETE',
    module: 'ROLES',
  },
  {
    name: 'Add a permission to role',
    apiPath: '/api/v1/roles/:id/permission/add',
    method: 'PATCH',
    module: 'ROLES',
  },
  {
    name: 'Create user',
    apiPath: '/api/v1/users',
    method: 'POST',
    module: 'USERS',
  },
  {
    name: 'Fetch user with pagination',
    apiPath: '/api/v1/users/get-user-with-pagination',
    method: 'GET',
    module: 'USERS',
  },
  {
    name: 'Get all users',
    apiPath: '/api/v1/users',
    method: 'GET',
    module: 'USERS',
  },
  {
    name: 'Fetch user by id',
    apiPath: '/api/v1/users/:id',
    method: 'GET',
    module: 'USERS',
  },
  {
    name: 'Update a user',
    apiPath: '/api/v1/users/update',
    method: 'PATCH',
    module: 'USERS',
  },
  {
    name: 'Delete a user',
    apiPath: '/api/v1/users/:id',
    method: 'DELETE',
    module: 'USERS',
  },
  {
    name: 'Create subscription plan',
    apiPath: '/api/v1/subscription-plans',
    method: 'POST',
    module: 'SUBSCRIPTION-PLANS',
  },
  {
    name: 'Get all subscription plans',
    apiPath: '/api/v1/subscription-plans',
    method: 'GET',
    module: 'SUBSCRIPTION-PLANS',
  },
  {
    name: 'Get subscription plan by id',
    apiPath: '/api/v1/subscription-plans/:id',
    method: 'GET',
    module: 'SUBSCRIPTION-PLANS',
  },
  {
    name: 'Update subscription plan',
    apiPath: '/api/v1/subscription-plans/:id',
    method: 'PATCH',
    module: 'SUBSCRIPTION-PLANS',
  },
  {
    name: 'Delete subscription plan',
    apiPath: '/api/v1/subscription-plans/:id',
    method: 'DELETE',
    module: 'SUBSCRIPTION-PLANS',
  },
  {
    name: 'Get films by actor',
    apiPath: '/api/v1/film-actor/get-films-by-actor/:actorId',
    method: 'GET',
    module: 'FILM-ACTOR',
  },
];
