export const INIT_PERMISSIONS = [
  {
    name: 'Create a list of actors',
    apiPath: '/api/v1/actor/create-list-actor',
    method: 'POST',
    module: 'ACTOR',
  },
  {
    name: 'Create an actor',
    apiPath: '/api/v1/actor/create-actor',
    method: 'POST',
    module: 'ACTOR',
  },
  {
    name: 'Get all actors',
    apiPath: '/api/v1/actor/all-actors',
    method: 'GET',
    module: 'ACTOR',
  },
  {
    name: 'Get actor by ID',
    apiPath: '/api/v1/actor/get-actor-by-id/:actorId',
    method: 'GET',
    module: 'ACTOR',
  },
  {
    name: 'Get actor by slug',
    apiPath: '/api/v1/actor/get-actor-by-slug/:actorSlug',
    method: 'GET',
    module: 'ACTOR',
  },
  {
    name: 'Update actor',
    apiPath: '/api/v1/actor/update-actor/:actorId',
    method: 'PATCH',
    module: 'ACTOR',
  },
  {
    name: 'Delete actor by ID',
    apiPath: '/api/v1/actor/delete-actor-by-id/:actorId',
    method: 'DELETE',
    module: 'ACTOR',
  },
  {
    name: 'Create all code',
    apiPath: '/api/v1/all-codes',
    method: 'POST',
    module: 'ALL-CODES',
  },
  {
    name: 'Get all codes',
    apiPath: '/api/v1/all-codes',
    method: 'GET',
    module: 'ALL-CODES',
  },
  {
    name: 'Get all code by ID',
    apiPath: '/api/v1/all-codes/:id',
    method: 'GET',
    module: 'ALL-CODES',
  },
  {
    name: 'Update all code',
    apiPath: '/api/v1/all-codes/:id',
    method: 'PATCH',
    module: 'ALL-CODES',
  },
  {
    name: 'Delete all code',
    apiPath: '/api/v1/all-codes/:id',
    method: 'DELETE',
    module: 'ALL-CODES',
  },
  {
    name: 'Get all code by type',
    apiPath: '/api/v1/all-codes/type/get-by-type',
    method: 'GET',
    module: 'ALL-CODES',
  },
  {
    name: 'User login',
    apiPath: '/api/v1/auth/login',
    method: 'POST',
    module: 'AUTH',
  },
  {
    name: 'Refresh token',
    apiPath: '/api/v1/auth/refreshToken',
    method: 'GET',
    module: 'AUTH',
  },
  {
    name: 'Get account information',
    apiPath: '/api/v1/auth/account',
    method: 'GET',
    module: 'AUTH',
  },
  {
    name: 'Register user',
    apiPath: '/api/v1/auth/register',
    method: 'POST',
    module: 'AUTH',
  },
  {
    name: 'Logout user',
    apiPath: '/api/v1/auth/logout',
    method: 'POST',
    module: 'AUTH',
  },
  {
    name: 'Chat with chatbot',
    apiPath: '/api/v1/chatbot/chat',
    method: 'POST',
    module: 'CHATBOT',
  },
  {
    name: 'Create co-watching session',
    apiPath: '/api/v1/co-watching',
    method: 'POST',
    module: 'CO-WATCHING',
  },
  {
    name: 'Get all co-watching sessions',
    apiPath: '/api/v1/co-watching',
    method: 'GET',
    module: 'CO-WATCHING',
  },
  {
    name: 'Get co-watching session by ID',
    apiPath: '/api/v1/co-watching/:id',
    method: 'GET',
    module: 'CO-WATCHING',
  },
  {
    name: 'Update co-watching session',
    apiPath: '/api/v1/co-watching/:id',
    method: 'PATCH',
    module: 'CO-WATCHING',
  },
  {
    name: 'Delete co-watching session',
    apiPath: '/api/v1/co-watching/:id',
    method: 'DELETE',
    module: 'CO-WATCHING',
  },
  {
    name: 'Create a comment',
    apiPath: '/api/v1/comment/create-comment',
    method: 'POST',
    module: 'COMMENT',
  },
  {
    name: 'Get comments by film (authenticated)',
    apiPath: '/api/v1/comment/get-comments-by-film/:filmId',
    method: 'GET',
    module: 'COMMENT',
  },
  {
    name: 'Get comments by film (guest)',
    apiPath: '/api/v1/comment/get-comments-by-film-guest/:filmId',
    method: 'GET',
    module: 'COMMENT',
  },
  {
    name: 'Get comment by ID',
    apiPath: '/api/v1/comment/get-comment/:commentId',
    method: 'GET',
    module: 'COMMENT',
  },
  {
    name: 'Update comment',
    apiPath: '/api/v1/comment/update-comment/:commentId',
    method: 'PATCH',
    module: 'COMMENT',
  },
  {
    name: 'Delete comment',
    apiPath: '/api/v1/comment/delete-comment/:commentId',
    method: 'DELETE',
    module: 'COMMENT',
  },
  {
    name: 'Toggle hide comment',
    apiPath: '/api/v1/comment/toggle-hide/:commentId',
    method: 'PATCH',
    module: 'COMMENT',
  },
  {
    name: 'Count comments by film',
    apiPath: '/api/v1/comment/count-by-film/:filmId',
    method: 'GET',
    module: 'COMMENT',
  },
  {
    name: 'Create comment reaction',
    apiPath: '/api/v1/comment-reactions/create-reaction',
    method: 'POST',
    module: 'COMMENT-REACTIONS',
  },
  {
    name: 'Create a director',
    apiPath: '/api/v1/director/create-director',
    method: 'POST',
    module: 'DIRECTOR',
  },
  {
    name: 'Get all directors',
    apiPath: '/api/v1/director/get-all-directors',
    method: 'GET',
    module: 'DIRECTOR',
  },
  {
    name: 'Get director by ID',
    apiPath: '/api/v1/director/get-director-by-id/:directorId',
    method: 'GET',
    module: 'DIRECTOR',
  },
  {
    name: 'Get director by slug',
    apiPath: '/api/v1/director/get-director-by-slug/:directorSlug',
    method: 'GET',
    module: 'DIRECTOR',
  },
  {
    name: 'Update director',
    apiPath: '/api/v1/director/edit-director/:directorId',
    method: 'PATCH',
    module: 'DIRECTOR',
  },
  {
    name: 'Delete director by ID',
    apiPath: '/api/v1/director/delete-director-by-id/:directorId',
    method: 'DELETE',
    module: 'DIRECTOR',
  },
  {
    name: 'Create an episode',
    apiPath: '/api/v1/episodes',
    method: 'POST',
    module: 'EPISODES',
  },
  {
    name: 'Create list of episodes',
    apiPath: '/api/v1/episodes/create-list',
    method: 'POST',
    module: 'EPISODES',
  },
  {
    name: 'Get all episodes',
    apiPath: '/api/v1/episodes',
    method: 'GET',
    module: 'EPISODES',
  },
  {
    name: 'Get episode by ID',
    apiPath: '/api/v1/episodes/:id',
    method: 'GET',
    module: 'EPISODES',
  },
  {
    name: 'Update episode',
    apiPath: '/api/v1/episodes/:id',
    method: 'PATCH',
    module: 'EPISODES',
  },
  {
    name: 'Delete episode',
    apiPath: '/api/v1/episodes/:id',
    method: 'DELETE',
    module: 'EPISODES',
  },
  {
    name: 'Toggle favorite film',
    apiPath: '/api/v1/favorites/toggle',
    method: 'POST',
    module: 'FAVORITES',
  },
  {
    name: 'Get favorite by ID',
    apiPath: '/api/v1/favorites/get-by-favid',
    method: 'GET',
    module: 'FAVORITES',
  },
  {
    name: 'Get user favorite list',
    apiPath: '/api/v1/favorites/get-user-favorite-list',
    method: 'GET',
    module: 'FAVORITES',
  },
  {
    name: 'Upload file',
    apiPath: '/api/v1/file/upload',
    method: 'POST',
    module: 'FILE',
  },
  {
    name: 'Create film-actor relation',
    apiPath: '/api/v1/film-actor/create-film-actor',
    method: 'POST',
    module: 'FILM-ACTOR',
  },
  {
    name: 'Get all film-actor relations',
    apiPath: '/api/v1/film-actor/all-film-actors',
    method: 'GET',
    module: 'FILM-ACTOR',
  },
  {
    name: 'Get film-actor by ID',
    apiPath: '/api/v1/film-actor/get-film-actor-by-id/:id',
    method: 'GET',
    module: 'FILM-ACTOR',
  },
  {
    name: 'Get actors by film',
    apiPath: '/api/v1/film-actor/get-actors-by-film/:filmId',
    method: 'GET',
    module: 'FILM-ACTOR',
  },
  {
    name: 'Get films by actor',
    apiPath: '/api/v1/film-actor/get-films-by-actor/:actorId',
    method: 'GET',
    module: 'FILM-ACTOR',
  },
  {
    name: 'Update film-actor relation',
    apiPath: '/api/v1/film-actor/edit-film-actor/:id',
    method: 'PATCH',
    module: 'FILM-ACTOR',
  },
  {
    name: 'Delete film-actor relation',
    apiPath: '/api/v1/film-actor/delete-film-actor-by-id/:id',
    method: 'DELETE',
    module: 'FILM-ACTOR',
  },
  {
    name: 'Get films grouped by actor',
    apiPath: '/api/v1/film-actor/group-films-by-actor-lodash',
    method: 'GET',
    module: 'FILM-ACTOR',
  },
  {
    name: 'Get films by actor slug',
    apiPath: '/api/v1/film-actor/get-films-by-actor-slug/:actorSlug',
    method: 'GET',
    module: 'FILM-ACTOR',
  },
  {
    name: 'Create film-director relation',
    apiPath: '/api/v1/film-director/create-film-director',
    method: 'POST',
    module: 'FILM-DIRECTOR',
  },
  {
    name: 'Get all film-director relations',
    apiPath: '/api/v1/film-director/all-film-directors',
    method: 'GET',
    module: 'FILM-DIRECTOR',
  },
  {
    name: 'Get film-director by ID',
    apiPath: '/api/v1/film-director/get-film-director-by-id/:id',
    method: 'GET',
    module: 'FILM-DIRECTOR',
  },
  {
    name: 'Get directors by film',
    apiPath: '/api/v1/film-director/by-film/:filmId',
    method: 'GET',
    module: 'FILM-DIRECTOR',
  },
  {
    name: 'Get films by director',
    apiPath: '/api/v1/film-director/by-director/:directorId',
    method: 'GET',
    module: 'FILM-DIRECTOR',
  },
  {
    name: 'Get films by director slug',
    apiPath: '/api/v1/film-director/by-director-slug/:directorSlug',
    method: 'GET',
    module: 'FILM-DIRECTOR',
  },
  {
    name: 'Update film-director relation',
    apiPath: '/api/v1/film-director/edit-film-director/:id',
    method: 'PATCH',
    module: 'FILM-DIRECTOR',
  },
  {
    name: 'Delete film-director relation',
    apiPath: '/api/v1/film-director/delete-film-director/:id',
    method: 'DELETE',
    module: 'FILM-DIRECTOR',
  },
  {
    name: 'Get grouped directors and films',
    apiPath: '/api/v1/film-director/group-directors-and-films-lodash',
    method: 'GET',
    module: 'FILM-DIRECTOR',
  },
  {
    name: 'Create film-producer relation',
    apiPath: '/api/v1/film-producer/create-film-producer',
    method: 'POST',
    module: 'FILM-PRODUCER',
  },
  {
    name: 'Get all film-producer relations',
    apiPath: '/api/v1/film-producer/all-film-producers',
    method: 'GET',
    module: 'FILM-PRODUCER',
  },
  {
    name: 'Get film-producer by ID',
    apiPath: '/api/v1/film-producer/get-film-producer-by-id/:id',
    method: 'GET',
    module: 'FILM-PRODUCER',
  },
  {
    name: 'Get producers by film',
    apiPath: '/api/v1/film-producer/by-film/:filmId',
    method: 'GET',
    module: 'FILM-PRODUCER',
  },
  {
    name: 'Get films by producer',
    apiPath: '/api/v1/film-producer/by-producer/:producerId',
    method: 'GET',
    module: 'FILM-PRODUCER',
  },
  {
    name: 'Update film-producer relation',
    apiPath: '/api/v1/film-producer/edit-film-producer/:id',
    method: 'PATCH',
    module: 'FILM-PRODUCER',
  },
  {
    name: 'Delete film-producer relation',
    apiPath: '/api/v1/film-producer/delete-film-producer/:id',
    method: 'DELETE',
    module: 'FILM-PRODUCER',
  },
  {
    name: 'Create a film',
    apiPath: '/api/v1/films',
    method: 'POST',
    module: 'FILMS',
  },
  {
    name: 'Get all films',
    apiPath: '/api/v1/films',
    method: 'GET',
    module: 'FILMS',
  },
  {
    name: 'Get film by ID',
    apiPath: '/api/v1/films/:id',
    method: 'GET',
    module: 'FILMS',
  },
  {
    name: 'Get film by slug',
    apiPath: '/api/v1/films/slug/:slug',
    method: 'GET',
    module: 'FILMS',
  },
  {
    name: 'Update film',
    apiPath: '/api/v1/films/:id',
    method: 'PATCH',
    module: 'FILMS',
  },
  {
    name: 'Delete film',
    apiPath: '/api/v1/films/:id',
    method: 'DELETE',
    module: 'FILMS',
  },
  {
    name: 'Get films by country',
    apiPath: '/api/v1/films/by-country/:countryValueEn',
    method: 'GET',
    module: 'FILMS',
  },
  {
    name: 'Get films by genre',
    apiPath: '/api/v1/films/by-genre/:genreValueEn',
    method: 'GET',
    module: 'FILMS',
  },
  {
    name: 'Get films by type',
    apiPath: '/api/v1/films/by-type/:typeValueEn',
    method: 'GET',
    module: 'FILMS',
  },
  {
    name: 'Search films with filters',
    apiPath: '/api/v1/films/filter/search',
    method: 'GET',
    module: 'FILMS',
  },
  {
    name: 'Create a markdown',
    apiPath: '/api/v1/markdowns',
    method: 'POST',
    module: 'MARKDOWNS',
  },
  {
    name: 'Get all markdowns',
    apiPath: '/api/v1/markdowns',
    method: 'GET',
    module: 'MARKDOWNS',
  },
  {
    name: 'Get markdown by ID',
    apiPath: '/api/v1/markdowns/:id',
    method: 'GET',
    module: 'MARKDOWNS',
  },
  {
    name: 'Update markdown',
    apiPath: '/api/v1/markdowns/:id',
    method: 'PATCH',
    module: 'MARKDOWNS',
  },
  {
    name: 'Delete markdown',
    apiPath: '/api/v1/markdowns/:id',
    method: 'DELETE',
    module: 'MARKDOWNS',
  },
  {
    name: 'Get notifications',
    apiPath: '/api/v1/notifications',
    method: 'GET',
    module: 'NOTIFICATIONS',
  },
  {
    name: 'Get unread count',
    apiPath: '/api/v1/notifications/unread-count',
    method: 'GET',
    module: 'NOTIFICATIONS',
  },
  {
    name: 'Mark notification as read',
    apiPath: '/api/v1/notifications/:id/read',
    method: 'PATCH',
    module: 'NOTIFICATIONS',
  },
  {
    name: 'Mark all notifications as read',
    apiPath: '/api/v1/notifications/read-all',
    method: 'PATCH',
    module: 'NOTIFICATIONS',
  },
  {
    name: 'Delete notification',
    apiPath: '/api/v1/notifications/:id',
    method: 'DELETE',
    module: 'NOTIFICATIONS',
  },
  {
    name: 'Create a part',
    apiPath: '/api/v1/parts',
    method: 'POST',
    module: 'PARTS',
  },
  {
    name: 'Get parts by film',
    apiPath: '/api/v1/parts/film',
    method: 'POST',
    module: 'PARTS',
  },
  {
    name: 'Get part by ID',
    apiPath: '/api/v1/parts/:id',
    method: 'GET',
    module: 'PARTS',
  },
  {
    name: 'Update part',
    apiPath: '/api/v1/parts/:id',
    method: 'PATCH',
    module: 'PARTS',
  },
  {
    name: 'Delete part',
    apiPath: '/api/v1/parts/:id',
    method: 'DELETE',
    module: 'PARTS',
  },
  {
    name: 'Create payment URL',
    apiPath: '/api/v1/payments',
    method: 'POST',
    module: 'PAYMENTS',
  },
  {
    name: 'VNPay return',
    apiPath: '/api/v1/payments/vnpay_return',
    method: 'GET',
    module: 'PAYMENTS',
  },
  {
    name: 'Query transaction',
    apiPath: '/api/v1/payments/querydr',
    method: 'POST',
    module: 'PAYMENTS',
  },
  {
    name: 'Refund payment',
    apiPath: '/api/v1/payments/refund',
    method: 'POST',
    module: 'PAYMENTS',
  },
  {
    name: 'Get all payments',
    apiPath: '/api/v1/payments',
    method: 'GET',
    module: 'PAYMENTS',
  },
  {
    name: 'Get payment by ID',
    apiPath: '/api/v1/payments/:id',
    method: 'GET',
    module: 'PAYMENTS',
  },
  {
    name: 'Update payment',
    apiPath: '/api/v1/payments/:id',
    method: 'PATCH',
    module: 'PAYMENTS',
  },
  {
    name: 'Delete payment',
    apiPath: '/api/v1/payments/:id',
    method: 'DELETE',
    module: 'PAYMENTS',
  },
  {
    name: 'Create a permission',
    apiPath: '/api/v1/permissions',
    method: 'POST',
    module: 'PERMISSIONS',
  },
  {
    name: 'Get all permissions',
    apiPath: '/api/v1/permissions',
    method: 'GET',
    module: 'PERMISSIONS',
  },
  {
    name: 'Get permissions with pagination',
    apiPath: '/api/v1/permissions/get-permission-with-pagination',
    method: 'GET',
    module: 'PERMISSIONS',
  },
  {
    name: 'Get permission by ID',
    apiPath: '/api/v1/permissions/:id',
    method: 'GET',
    module: 'PERMISSIONS',
  },
  {
    name: 'Update permission',
    apiPath: '/api/v1/permissions/:id',
    method: 'PATCH',
    module: 'PERMISSIONS',
  },
  {
    name: 'Delete permission',
    apiPath: '/api/v1/permissions/:id',
    method: 'DELETE',
    module: 'PERMISSIONS',
  },
  {
    name: 'Create playlist-film relation',
    apiPath: '/api/v1/playlist-film',
    method: 'POST',
    module: 'PLAYLIST-FILM',
  },
  {
    name: 'Get all playlist-film relations',
    apiPath: '/api/v1/playlist-film',
    method: 'GET',
    module: 'PLAYLIST-FILM',
  },
  {
    name: 'Get playlist-film by ID',
    apiPath: '/api/v1/playlist-film/:id',
    method: 'GET',
    module: 'PLAYLIST-FILM',
  },
  {
    name: 'Update playlist-film relation',
    apiPath: '/api/v1/playlist-film/:id',
    method: 'PATCH',
    module: 'PLAYLIST-FILM',
  },
  {
    name: 'Delete playlist-film relation',
    apiPath: '/api/v1/playlist-film/:id',
    method: 'DELETE',
    module: 'PLAYLIST-FILM',
  },
  {
    name: 'Create playlist',
    apiPath: '/api/v1/playlists',
    method: 'POST',
    module: 'PLAYLISTS',
  },
  {
    name: 'Get user playlists',
    apiPath: '/api/v1/playlists/all-playlist',
    method: 'GET',
    module: 'PLAYLISTS',
  },
  {
    name: 'Get playlist detail',
    apiPath: '/api/v1/playlists/:id',
    method: 'GET',
    module: 'PLAYLISTS',
  },
  {
    name: 'Add film to playlist',
    apiPath: '/api/v1/playlists/add-film',
    method: 'POST',
    module: 'PLAYLISTS',
  },
  {
    name: 'Remove film from playlist',
    apiPath: '/api/v1/playlists/:id/film/:filmId',
    method: 'DELETE',
    module: 'PLAYLISTS',
  },
  {
    name: 'Delete playlist',
    apiPath: '/api/v1/playlists/remove-playlist/:playlistId',
    method: 'DELETE',
    module: 'PLAYLISTS',
  },
  {
    name: 'Edit playlist',
    apiPath: '/api/v1/playlists/edit-playlist/:playlistId',
    method: 'PATCH',
    module: 'PLAYLISTS',
  },
  {
    name: 'Create a producer',
    apiPath: '/api/v1/producer/create-producer',
    method: 'POST',
    module: 'PRODUCER',
  },
  {
    name: 'Get all producers',
    apiPath: '/api/v1/producer/get-all-producers',
    method: 'GET',
    module: 'PRODUCER',
  },
  {
    name: 'Get producer by ID',
    apiPath: '/api/v1/producer/get-producer-by-id/:producerId',
    method: 'GET',
    module: 'PRODUCER',
  },
  {
    name: 'Update producer',
    apiPath: '/api/v1/producer/edit-producer/:producerId',
    method: 'PATCH',
    module: 'PRODUCER',
  },
  {
    name: 'Delete producer by ID',
    apiPath: '/api/v1/producer/delete-producer-by-id/:producerId',
    method: 'DELETE',
    module: 'PRODUCER',
  },
  {
    name: 'Create rating',
    apiPath: '/api/v1/rating/create-rating',
    method: 'POST',
    module: 'RATING',
  },
  {
    name: 'Get ratings by film',
    apiPath: '/api/v1/rating/get-rating-by-film/:filmId',
    method: 'GET',
    module: 'RATING',
  },
  {
    name: 'Delete rating',
    apiPath: '/api/v1/rating/delete-rating/:ratingId',
    method: 'DELETE',
    module: 'RATING',
  },
  {
    name: 'Create role-permission relation',
    apiPath: '/api/v1/role-permission',
    method: 'POST',
    module: 'ROLE-PERMISSION',
  },
  {
    name: 'Delete role-permission relation',
    apiPath: '/api/v1/role-permission/delete',
    method: 'DELETE',
    module: 'ROLE-PERMISSION',
  },
  {
    name: 'Get permissions by role',
    apiPath: '/api/v1/role-permission/by-role/:roleId',
    method: 'GET',
    module: 'ROLE-PERMISSION',
  },
  {
    name: 'Get roles by permission',
    apiPath: '/api/v1/role-permission/by-permission/:permissionId',
    method: 'GET',
    module: 'ROLE-PERMISSION',
  },
  {
    name: 'Create a role',
    apiPath: '/api/v1/roles',
    method: 'POST',
    module: 'ROLES',
  },
  {
    name: 'Get all roles',
    apiPath: '/api/v1/roles',
    method: 'GET',
    module: 'ROLES',
  },
  {
    name: 'Get role by ID',
    apiPath: '/api/v1/roles/:id',
    method: 'GET',
    module: 'ROLES',
  },
  {
    name: 'Get role by ID (alternative)',
    apiPath: '/api/v1/roles/get-by-id/:id',
    method: 'GET',
    module: 'ROLES',
  },
  {
    name: 'Update role',
    apiPath: '/api/v1/roles/:id',
    method: 'PATCH',
    module: 'ROLES',
  },
  {
    name: 'Delete role',
    apiPath: '/api/v1/roles/:id',
    method: 'DELETE',
    module: 'ROLES',
  },
  {
    name: 'Check role before delete',
    apiPath: '/api/v1/roles/:id/check-delete',
    method: 'GET',
    module: 'ROLES',
  },
  {
    name: 'Reassign users and delete role',
    apiPath: '/api/v1/roles/:id/reassign-and-delete',
    method: 'POST',
    module: 'ROLES',
  },
  {
    name: 'Restore role',
    apiPath: '/api/v1/roles/:id/restore',
    method: 'PATCH',
    module: 'ROLES',
  },
  {
    name: 'Search films',
    apiPath: '/api/v1/search/films',
    method: 'GET',
    module: 'SEARCH',
  },
  {
    name: 'Delete films index',
    apiPath: '/api/v1/search/films',
    method: 'DELETE',
    module: 'SEARCH',
  },
  {
    name: 'Sync films to index',
    apiPath: '/api/v1/search/sync/films',
    method: 'GET',
    module: 'SEARCH',
  },
  {
    name: 'Get all films from index',
    apiPath: '/api/v1/search/get-All-Films-From-Index',
    method: 'GET',
    module: 'SEARCH',
  },
  {
    name: 'Count films in index',
    apiPath: '/api/v1/search/films/count',
    method: 'GET',
    module: 'SEARCH',
  },
  {
    name: 'Delete film from index',
    apiPath: '/api/v1/search/films/:filmId',
    method: 'DELETE',
    module: 'SEARCH',
  },
  {
    name: 'Delete all documents in films index',
    apiPath: '/api/v1/search/delete-all',
    method: 'DELETE',
    module: 'SEARCH',
  },
  {
    name: 'Create subscription plan',
    apiPath: '/api/v1/subscription-plans',
    method: 'POST',
    module: 'SUBSCRIPTION-PLANS',
  },
  {
    name: 'Get all subscription plans',
    apiPath: '/api/v1/subscription-plans',
    method: 'GET',
    module: 'SUBSCRIPTION-PLANS',
  },
  {
    name: 'Get subscription plan by ID',
    apiPath: '/api/v1/subscription-plans/:id',
    method: 'GET',
    module: 'SUBSCRIPTION-PLANS',
  },
  {
    name: 'Update subscription plan',
    apiPath: '/api/v1/subscription-plans/:id',
    method: 'PATCH',
    module: 'SUBSCRIPTION-PLANS',
  },
  {
    name: 'Delete subscription plan',
    apiPath: '/api/v1/subscription-plans/:id',
    method: 'DELETE',
    module: 'SUBSCRIPTION-PLANS',
  },
  {
    name: 'Create subscription',
    apiPath: '/api/v1/subscriptions',
    method: 'POST',
    module: 'SUBSCRIPTIONS',
  },
  {
    name: 'Get all subscriptions',
    apiPath: '/api/v1/subscriptions',
    method: 'GET',
    module: 'SUBSCRIPTIONS',
  },
  {
    name: 'Get subscription by user ID',
    apiPath: '/api/v1/subscriptions/get-by-id',
    method: 'GET',
    module: 'SUBSCRIPTIONS',
  },
  {
    name: 'Update subscription',
    apiPath: '/api/v1/subscriptions/:id',
    method: 'PATCH',
    module: 'SUBSCRIPTIONS',
  },
  {
    name: 'Delete subscription',
    apiPath: '/api/v1/subscriptions/:id',
    method: 'DELETE',
    module: 'SUBSCRIPTIONS',
  },
  {
    name: 'Create a user',
    apiPath: '/api/v1/users',
    method: 'POST',
    module: 'USERS',
  },
  {
    name: 'Get users with pagination',
    apiPath: '/api/v1/users/get-user-with-pagination',
    method: 'GET',
    module: 'USERS',
  },
  {
    name: 'Get all users',
    apiPath: '/api/v1/users',
    method: 'GET',
    module: 'USERS',
  },
  {
    name: 'Get user by ID',
    apiPath: '/api/v1/users/:id',
    method: 'GET',
    module: 'USERS',
  },
  {
    name: 'Update user',
    apiPath: '/api/v1/users/update',
    method: 'PATCH',
    module: 'USERS',
  },
  {
    name: 'Update user profile',
    apiPath: '/api/v1/users/update-profile',
    method: 'PATCH',
    module: 'USERS',
  },
  {
    name: 'Delete user',
    apiPath: '/api/v1/users/:id',
    method: 'DELETE',
    module: 'USERS',
  },
];
